
services:
  app:
    build:
      context: .
      target: development
    container_name: http_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - localstack
      - elasticsearch
      - kibana
      - swagger

  app-front:
    build:
      context: .
      target: front-development
    container_name: front_app
    ports:
      - "8050:8050"
    volumes:
      - .:/app
      
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      SWAGGER_YAML: /usr/share/nginx/html/openapi.yaml

  tests:
    build:
      context: .
      target: test
    container_name: fastapi_tests
    volumes:
      - .:/app
    depends_on:
      - localstack
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
       - "5601:5601"
    environment:
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
       - elasticsearch

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=lambda,events,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  lambda_runtime:
    build:
      context: .
      target: lambda_runtime
    container_name: lambda_runtime
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - localstack

volumes:
  postgres_data:
  es_data: