
services:
  app:
    build:
      context: .
      target: development
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: http://app:8000/openapi.json
    depends_on:
      - app

  tests:
    build:
      context: .
      target: test
    container_name: fastapi_tests
    volumes:
      - .:/app
    depends_on:
      - app
      - db
      - redis

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
       - "5601:5601"
    environment:
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
       - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=lambda,events
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  lambda:
    build:
      context: .
      target: development-lambda
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1  
    ports:
      - "9001:9001"

volumes:
  postgres_data:
  es_data: